---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonarqube-setup
  labels:
    app: sonarqube-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: edit-sonarqube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: sonarqube-setup
---
apiVersion: v1
kind: ConfigMap
data:
  config-sonarqube.sh: |-
    {{- include "config-sonarqube" . | indent 4 }}
metadata:
  name: sonarqubesetup
  labels:
    app: sonarqube-setup
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sonarqube-setup
  labels:
    app: sonarqube-setup
spec:
  template:
    metadata:
      name: sonarqube-setup-job
    spec:
      restartPolicy: OnFailure
      serviceAccountName: sonarqube-setup
      volumes:
      - configMap:
          defaultMode: 420
          name: sonarqubesetup
        name: sonarqubesetup
      containers:
      - name: ss
        image: quay.io/eformat/openshift-helm:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "source /tmp/config-sonarqube.sh"
        volumeMounts:
        - mountPath: /tmp/config-sonarqube.sh
          name: sonarqubesetup
          subPath: config-sonarqube.sh
